services:
  jumpcut-api:
    build: .
    container_name: jumpcut-docker
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      # Geçici dosyalar için volume (opsiyonel)
      - temp_files:/tmp
    restart: unless-stopped
    environment:
      - PORT=5000

volumes:
  temp_files:

